# Generated by Django 4.2 on 2023-05-02 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_id_alter_review_id_alter_tag_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, default='default_img.jpeg', null=True, upload_to=''),
        ),
    ]
